services:
  app:
    build:
      context: .
      target: development
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
  server:
    image: nginx:1.27.2
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/:ro
      - ./:/app:ro

  db:
    image: mysql:9.1.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
# secrets:
#   db-password:
#     file: db/password.txt

